load("@rules_robotpy_utils//rules_robotpy_utils:pybind_rules.bzl", "create_pybind_library")
load("@rules_robotpy_utils//rules_robotpy_utils:generate_robotpy_project_files.bzl", "generate_robotpy_project_files")

generate_robotpy_project_files(
    name = "example",
    config_file = "//python:config_file",
    # visibility = ["//wpiutil/src/main/python:__subpackages__"],
)

create_pybind_library(
    "example",
    entry_point = ["main.cpp"],
    generation_helper_prefix = "//python:example",
    deps = [
        "//cpp:example",
    ],
)
