# fmt: off
# This file is automatically generated, DO NOT EDIT

from os.path import abspath, join, dirname
_root = abspath(dirname(__file__))

libinit_import = "example._init_example"
depends = []
pypi_package = 'project_name'

def get_include_dirs():
    return [join(_root, "include"), join(_root, "rpy-include"), join(_root, "src", "type_casters")]

def get_library_dirs():
    return []

def get_library_dirs_rel():
    return []

def get_library_names():
    return []

def get_library_full_names():
    return []
